openapi: 3.2.0
info:
  title: ACCOUNT DATA - Client Hosted Account Verification - Client Hosted API
  version: '1.0'
servers:
- url: https://test.api.ordopay.com/client
security:
- apiKeyHeader: []
- apiKeyQuery: []
tags:
- name: Account Verification - Client Hosted
paths:
  /account/verification/create:
    post:
      tags:
      - Account Verification - Client Hosted
      summary: Creates a new AV request
      description: Creates a new AV request
      operationId: post-account-verification-create
      parameters:
      - name: participantId
        in: header
        description: Format - int32.
        schema:
          type: integer
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AVRequest'
            example:
              clientReference: string
              expiryDate: string
              avurLs:
                redirectURL: string
                cancelURL: string
                errorURL: string
          text/json:
            schema:
              $ref: '#/components/schemas/AVRequest'
            example:
              clientReference: string
              expiryDate: string
              avurLs:
                redirectURL: string
                cancelURL: string
                errorURL: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/AVRequest'
            example:
              clientReference: string
              expiryDate: string
              avurLs:
                redirectURL: string
                cancelURL: string
                errorURL: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AVPostResponse'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/AVPostResponse'
              example:
                av:
                  avId: string
                  createdDate: string
                  createdBy: string
                  expiryDate: string
                  updatedDate: string
                  updatedBy: string
                  clientReference: string
                  participantId: 0
                  status: string
                avAuthUrl: string
                avURLs:
                  redirectURL: string
                  cancelURL: string
                  errorURL: string
            text/json:
              schema:
                $ref: '#/components/schemas/AVPostResponse'
              example:
                av:
                  avId: string
                  createdDate: string
                  createdBy: string
                  expiryDate: string
                  updatedDate: string
                  updatedBy: string
                  clientReference: string
                  participantId: 0
                  status: string
                avAuthUrl: string
                avURLs:
                  redirectURL: string
                  cancelURL: string
                  errorURL: string
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorCode: string
                errorMessage: string
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorCode: string
                errorMessage: string
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
        '403':
          description: Forbidden
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '422':
          description: Client Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
  /account/verification/initiate:
    post:
      tags:
      - Account Verification - Client Hosted
      summary: Initiate an AV request
      description: Initiate an AV request
      operationId: post-account-verification-clienthostedinitiate
      parameters:
      - name: participantId
        in: header
        description: Format - int32.
        schema:
          type: integer
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientHostedInitiateAVRequest'
            example:
              ordoInstitutionId: string
              avId: string
          text/json:
            schema:
              $ref: '#/components/schemas/ClientHostedInitiateAVRequest'
            example:
              ordoInstitutionId: string
              avId: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/ClientHostedInitiateAVRequest'
            example:
              ordoInstitutionId: string
              avId: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AccountAuthResponse'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAuthResponse'
              example:
                authorisationUrl: string
            text/json:
              schema:
                $ref: '#/components/schemas/AccountAuthResponse'
              example:
                authorisationUrl: string
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
        '403':
          description: Forbidden
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '422':
          description: Client Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
  /account/verification/institutions:
    get:
      tags:
      - Account Verification - Client Hosted
      summary: Gets a list of AV enabled institutions
      description: Gets a list of AV enabled institutions
      operationId: get-account-verification-institutions
      parameters:
      - name: OrdoInstitutionId
        in: query
        schema:
          type: string
      - name: participantId
        in: header
        description: Format - int32. Participant ID in the header
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/InstitutionResponse'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/InstitutionResponse'
              example:
                ordoInstitutionId: string
                name: string
                media:
                  iconUrl: string
                  logoUrl: string
                refundDataAvailable: true
                aisEnabled: true
                features:
                - string
            text/json:
              schema:
                $ref: '#/components/schemas/InstitutionResponse'
              example:
                ordoInstitutionId: string
                name: string
                media:
                  iconUrl: string
                  logoUrl: string
                refundDataAvailable: true
                aisEnabled: true
                features:
                - string
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorCode: string
                errorMessage: string
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorCode: string
                errorMessage: string
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
        '403':
          description: Forbidden
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '422':
          description: Client Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
  /account/verification/{avId}:
    get:
      tags:
      - Account Verification - Client Hosted
      summary: Get an AV request
      description: Returns AV Record
      operationId: get-account-verification-avid
      parameters:
      - name: avId
        in: path
        description: ''
        required: true
        schema:
          type: string
      - name: participantId
        in: header
        description: Format - int32.
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GetAVRecord'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/GetAVRecord'
              example:
                avId: string
                participantId: 0
                billerApprovedName: string
                clientReference: string
                status: string
                createdDate: string
                createdBy: string
                expiryDate: string
                avURLs:
                  redirectURL: string
                  cancelURL: string
                  errorURL: string
            text/json:
              schema:
                $ref: '#/components/schemas/GetAVRecord'
              example:
                avId: string
                participantId: 0
                billerApprovedName: string
                clientReference: string
                status: string
                createdDate: string
                createdBy: string
                expiryDate: string
                avURLs:
                  redirectURL: string
                  cancelURL: string
                  errorURL: string
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
        '403':
          description: Forbidden
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '422':
          description: Client Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
  /account/verification/account:
    get:
      tags:
      - Account Verification - Client Hosted
      summary: Gets all AV accounts for a participant
      description: Returns all AV accounts for a participant
      operationId: get-account-verification-account
      parameters:
      - name: participantId
        in: header
        description: Format - int32.
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AVAccountGetResponse'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/AVAccountGetResponse'
              example:
                avId: string
                participantId: 0
                accounts:
                - accountId: string
                  type: string
                  subType: string
                  schemeName: string
                  currency: string
                  accountName: string
                  sortCode: string
                  accountNumber: string
                  iban: string
                  pan: string
            text/json:
              schema:
                $ref: '#/components/schemas/AVAccountGetResponse'
              example:
                avId: string
                participantId: 0
                accounts:
                - accountId: string
                  type: string
                  subType: string
                  schemeName: string
                  currency: string
                  accountName: string
                  sortCode: string
                  accountNumber: string
                  iban: string
                  pan: string
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
        '403':
          description: Forbidden
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '422':
          description: Client Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
  /account/verification/account/{avId}:
    get:
      tags:
      - Account Verification - Client Hosted
      summary: Get AV account data
      description: Returns AV Account Details for specified AV ID
      operationId: get-account-verification-account-avid
      parameters:
      - name: avId
        in: path
        description: ''
        required: true
        schema:
          type: string
      - name: participantId
        in: header
        description: Format - int32.
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AVAccountGetResponse'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/AVAccountGetResponse'
              example:
                avId: string
                participantId: 0
                accounts:
                - accountId: string
                  type: string
                  subType: string
                  schemeName: string
                  currency: string
                  accountName: string
                  sortCode: string
                  accountNumber: string
                  iban: string
                  pan: string
            text/json:
              schema:
                $ref: '#/components/schemas/AVAccountGetResponse'
              example:
                avId: string
                participantId: 0
                accounts:
                - accountId: string
                  type: string
                  subType: string
                  schemeName: string
                  currency: string
                  accountName: string
                  sortCode: string
                  accountNumber: string
                  iban: string
                  pan: string
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
        '403':
          description: Forbidden
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '422':
          description: Client Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/OrdoValidationProblemDetails'
              example:
                title: string
                status: 0
                detail: string
                code: string
                errors: {}
                type: string
                instance: string
components:
  schemas:
    MediaElement:
      type: object
      properties:
        iconUrl:
          type:
          - string
          - 'null'
          format: uri
        logoUrl:
          type:
          - string
          - 'null'
          format: uri
      additionalProperties: false
    ErrorResponse:
      type: object
      properties:
        errorCode:
          type:
          - string
          - 'null'
        errorMessage:
          type:
          - string
          - 'null'
      additionalProperties: false
    AccountAuthResponse:
      type: object
      properties:
        authorisationUrl:
          type:
          - string
          - 'null'
      additionalProperties: false
    AVAccountGetResponse:
      type: object
      properties:
        aVid:
          type:
          - string
          - 'null'
        participantId:
          type: integer
          format: int32
        accounts:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OBAccount'
      additionalProperties: false
    ClientHostedInitiateAVRequest:
      required:
      - avId
      - ordoInstitutionId
      type: object
      properties:
        ordoInstitutionId:
          type: string
        avId:
          type: string
      additionalProperties: false
    AVPostResponse:
      type: object
      properties:
        av:
          $ref: '#/components/schemas/AVResponse'
        avAuthUrl:
          type:
          - string
          - 'null'
        avURLs:
          $ref: '#/components/schemas/AVURLs'
      additionalProperties: false
    InstitutionResponse:
      type: object
      properties:
        ordoInstitutionId:
          type:
          - string
          - 'null'
        name:
          type:
          - string
          - 'null'
        media:
          $ref: '#/components/schemas/MediaElement'
        refundDataAvailable:
          type: boolean
        aisEnabled:
          type: boolean
        features:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
    AVURLs:
      type: object
      properties:
        redirectURL:
          type:
          - string
          - 'null'
        cancelURL:
          type:
          - string
          - 'null'
        errorURL:
          type:
          - string
          - 'null'
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        status:
          type:
          - integer
          - 'null'
          format: int32
        detail:
          type:
          - string
          - 'null'
        instance:
          type:
          - string
          - 'null'
      additionalProperties: {}
    GetAVRecord:
      type: object
      properties:
        avId:
          type:
          - string
          - 'null'
        participantId:
          type: integer
          format: int32
        billerApprovedName:
          type:
          - string
          - 'null'
        clientReference:
          type:
          - string
          - 'null'
        status:
          type:
          - string
          - 'null'
        createdDate:
          type: string
          format: date-time
        createdBy:
          type:
          - string
          - 'null'
        expiryDate:
          type:
          - string
          - 'null'
          format: date-time
        avURLs:
          $ref: '#/components/schemas/AVURLs'
      additionalProperties: false
    AVResponse:
      type: object
      properties:
        avId:
          type:
          - string
          - 'null'
        createdDate:
          type: string
          format: date-time
        createdBy:
          type:
          - string
          - 'null'
        updatedDate:
          type:
          - string
          - 'null'
          format: date-time
        updatedBy:
          type:
          - string
          - 'null'
        clientReference:
          type:
          - string
          - 'null'
        participantId:
          type: integer
          format: int32
        status:
          type:
          - string
          - 'null'
      additionalProperties: false
    OrdoValidationProblemDetails:
      type: object
      properties:
        title:
          type:
          - string
          - 'null'
        status:
          type:
          - integer
          - 'null'
          format: int32
        detail:
          type:
          - string
          - 'null'
        code:
          type:
          - string
          - 'null'
        errors:
          type:
          - object
          - 'null'
          additionalProperties:
            type: array
            items:
              type: string
          readOnly: true
        type:
          type:
          - string
          - 'null'
        instance:
          type:
          - string
          - 'null'
      additionalProperties: {}
    OBAccount:
      type: object
      properties:
        accountId:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        subType:
          type:
          - string
          - 'null'
        schemeName:
          type:
          - string
          - 'null'
        currency:
          type:
          - string
          - 'null'
        accountName:
          type:
          - string
          - 'null'
        sortCode:
          type:
          - string
          - 'null'
        accountNumber:
          type:
          - string
          - 'null'
        iban:
          type:
          - string
          - 'null'
        pan:
          type:
          - string
          - 'null'
      additionalProperties: false
    AVRequest:
      type: object
      properties:
        clientReference:
          type:
          - string
          - 'null'
        avurLs:
          $ref: '#/components/schemas/AVURLs'
      additionalProperties: false
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
x-readme:
  explorer-enabled: true
  proxy-enabled: true
